# manipulator:
#  kinematics_solver: ur_kinematics/UR3eKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005
manipulator:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: Distance #Distance, Speed, Manipulation1, Manipulation2
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.01
  goal_joint_tolerance: 0.0001
  goal_position_tolerance: 0.0001
  goal_orientation_tolerance: 0.001